export let paddingClasses = {
    left: {
        xxs:'d-pl-xxs',
        xs:'d-pl-xs',
        s:'d-pl-s',
        m:'d-pl-m',
        l:'d-pl-l',
        xl:'d-pl-xl',
        xxl:'d-pl-xxl',
    },
    right: {
        xxs:'d-pr-xxs',
        xs:'d-pr-xs',
        s:'d-pr-s',
        m:'d-pr-m',
        l:'d-pr-l',
        xl:'d-pr-xl',
        xxl:'d-pr-xxl',
    },
    top: {
        xxs:'d-pt-xxs',
        xs:'d-pt-xs',
        s:'d-pt-s',
        m:'d-pt-m',
        l:'d-pt-l',
        xl:'d-pt-xl',
        xxl:'d-pt-xxl',
    },
    bottom: {
        xxs:'d-pb-xxs',
        xs:'d-pb-xs',
        s:'d-pb-s',
        m:'d-pb-m',
        l:'d-pb-l',
        xl:'d-pb-xl',
        xxl:'d-pb-xxl',
    },
    x: {
        xxs:'d-px-xxs',
        xs:'d-px-xs',
        s:'d-px-s',
        m:'d-px-m',
        l:'d-px-l',
        xl:'d-px-xl',
        xxl:'d-px-xxl',
    },
    y: {
        xxs:'d-py-xxs',
        xs:'d-py-xs',
        s:'d-py-s',
        m:'d-py-m',
        l:'d-py-l',
        xl:'d-py-xl',
        xxl:'d-py-xxl',
    },
    all: {
        xxs:'d-pa-xxs',
        xs:'d-pa-xs',
        s:'d-pa-s',
        m:'d-pa-m',
        l:'d-pa-l',
        xl:'d-pa-xl',
        xxl:'d-pa-xxl',
    }
};

export let marginClasses = {
    left: {
        xxs:'d-ml-xxs',
        xs:'d-ml-xs',
        s:'d-ml-s',
        m:'d-ml-m',
        l:'d-ml-l',
        xl:'d-ml-xl',
        xxl:'d-ml-xxl',
    },
    right: {
        xxs:'d-mr-xxs',
        xs:'d-mr-xs',
        s:'d-mr-s',
        m:'d-mr-m',
        l:'d-mr-l',
        xl:'d-mr-xl',
        xxl:'d-mr-xxl',
    },
    top: {
        xxs:'d-mt-xxs',
        xs:'d-mt-xs',
        s:'d-mt-s',
        m:'d-mt-m',
        l:'d-mt-l',
        xl:'d-mt-xl',
        xxl:'d-mt-xxl',
    },
    bottom: {
        xxs:'d-mb-xxs',
        xs:'d-mb-xs',
        s:'d-mb-s',
        m:'d-mb-m',
        l:'d-mb-l',
        xl:'d-mb-xl',
        xxl:'d-mb-xxl',
    },
    x: {
        xxs:'d-mx-xxs',
        xs:'d-mx-xs',
        s:'d-mx-s',
        m:'d-mx-m',
        l:'d-mx-l',
        xl:'d-mx-xl',
        xxl:'d-mx-xxl',
    },
    y: {
        xxs:'d-my-xxs',
        xs:'d-my-xs',
        s:'d-my-s',
        m:'d-my-m',
        l:'d-my-l',
        xl:'d-my-xl',
        xxl:'d-my-xxl',
    },
    all: {
        xxs:'d-ma-xxs',
        xs:'d-ma-xs',
        s:'d-ma-s',
        m:'d-ma-m',
        l:'d-ma-l',
        xl:'d-ma-xl',
        xxl:'d-ma-xxl',
    }
}
